// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Data
{


    public class minhasTarefasContext : System.Data.Entity.DbContext, IminhasTarefasContext
    {
        public System.Data.Entity.DbSet<TblLista> TblListas { get; set; } // TBL_Lista
        public System.Data.Entity.DbSet<TblListaTarefa> TblListaTarefas { get; set; } // TBL_Lista_Tarefa
        public System.Data.Entity.DbSet<TblTarefa> TblTarefas { get; set; } // TBL_Tarefa

        static minhasTarefasContext()
        {
            System.Data.Entity.Database.SetInitializer<minhasTarefasContext>(null);
        }

        public minhasTarefasContext()
            : base("Name=minhasTarefasContext")
        {
        }

        public minhasTarefasContext(string connectionString)
            : base(connectionString)
        {
        }

        public minhasTarefasContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public minhasTarefasContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public minhasTarefasContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new TblListaConfiguration());
            modelBuilder.Configurations.Add(new TblListaTarefaConfiguration());
            modelBuilder.Configurations.Add(new TblTarefaConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new TblListaConfiguration(schema));
            modelBuilder.Configurations.Add(new TblListaTarefaConfiguration(schema));
            modelBuilder.Configurations.Add(new TblTarefaConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
