// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Data
{

    // TBL_Lista_Tarefa
    public class TblListaTarefa
    {
        public int Id { get; set; } // Id (Primary key)
        public int IdLista { get; set; } // IdLista
        public int IdTarefa { get; set; } // IdTarefa
        public System.DateTime DataAlteracao { get; set; } // DataAlteracao

        // Foreign keys

        /// <summary>
        /// Parent TblLista pointed by [TBL_Lista_Tarefa].([IdLista]) (FK_TBL_Lista_Tarefa_Lista)
        /// </summary>
        public virtual TblLista TblLista { get; set; } // FK_TBL_Lista_Tarefa_Lista

        /// <summary>
        /// Parent TblTarefa pointed by [TBL_Lista_Tarefa].([IdTarefa]) (FK_TBL_Lista_Tarefa_Tarefa)
        /// </summary>
        public virtual TblTarefa TblTarefa { get; set; } // FK_TBL_Lista_Tarefa_Tarefa
    }

}
// </auto-generated>
