// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Data
{

    // TBL_Tarefa
    public class TblTarefa
    {
        public int Id { get; set; } // Id (Primary key)
        public string Nome { get; set; } // Nome (length: 250)
        public bool Ativo { get; set; } // Ativo
        public System.DateTime DataAlteracao { get; set; } // DataAlteracao
        public bool Importante { get; set; } // Importante
        public int Prioridade { get; set; } // Prioridade

        // Reverse navigation

        /// <summary>
        /// Child TblListaTarefas where [TBL_Lista_Tarefa].[IdTarefa] point to this entity (FK_TBL_Lista_Tarefa_Tarefa)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TblListaTarefa> TblListaTarefas { get; set; } // TBL_Lista_Tarefa.FK_TBL_Lista_Tarefa_Tarefa

        public TblTarefa()
        {
            TblListaTarefas = new System.Collections.Generic.List<TblListaTarefa>();
        }
    }

}
// </auto-generated>
